# Generated by Django 3.2.9 on 2022-05-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performs', '0002_alter_rating_perform'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата')),
                ('url', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
