# Generated by Django 3.2.9 on 2022-05-02 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performs', '0003_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performshorts',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
    ]
