# Generated by Django 3.2.9 on 2022-05-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performs', '0004_alter_performshorts_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='position',
            field=models.CharField(default='', max_length=150, verbose_name='Должность'),
        ),
    ]
