# Generated by Django 3.2.9 on 2022-05-02 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performs', '0005_people_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='perform',
            name='date1',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Выступление_1'),
        ),
        migrations.AddField(
            model_name='perform',
            name='date2',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Выступление_2'),
        ),
        migrations.AddField(
            model_name='perform',
            name='date3',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Выступление_3'),
        ),
    ]
