# Generated by Django 3.2.9 on 2022-05-15 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performs', '0007_auto_20220515_1006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerformShorts',
            new_name='PerformShots',
        ),
    ]
