# Generated by Django 3.2.9 on 2022-05-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performs', '0009_perform_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='perform',
            name='composer',
            field=models.ManyToManyField(default='Голланд', related_name='perform_composer', to='performs.People', verbose_name='композитор'),
        ),
    ]
