# Generated by Django 3.2.9 on 2022-05-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performs', '0010_perform_composer'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='preview',
            field=models.TextField(default='Новость', verbose_name='Краткое описание'),
        ),
    ]
