# Generated by Django 3.2.9 on 2022-05-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performs', '0011_news_preview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Звезда рейтинга', 'verbose_name_plural': 'Звезды рейтинга'},
        ),
        migrations.RemoveField(
            model_name='perform',
            name='category',
        ),
        migrations.AddField(
            model_name='perform',
            name='categories',
            field=models.ManyToManyField(default='жбр', related_name='perform_composer', to='performs.Category', verbose_name='категория'),
        ),
    ]
