# Generated by Django 3.2.9 on 2022-05-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performs', '0022_alter_reviews_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.IntegerField()),
                ('occupant_first_name', models.CharField(max_length=255)),
                ('occupant_last_name', models.CharField(max_length=255)),
                ('occupant_email', models.EmailField(max_length=555)),
                ('purchase_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='perform',
            name='price',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='perform',
            name='booked_seats',
            field=models.ManyToManyField(blank=True, to='performs.Seat'),
        ),
    ]
