# Generated by Django 3.2.9 on 2022-05-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performs', '0023_auto_20220531_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perform',
            name='price',
            field=models.IntegerField(default=500, verbose_name='Цена билета'),
        ),
    ]
