# Generated by Django 2.2.28 on 2022-06-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performs', '0025_auto_20220602_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='occupant_email',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='occupant_first_name',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='occupant_last_name',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='purchase_time',
        ),
        migrations.AddField(
            model_name='seat',
            name='book',
            field=models.BooleanField(default=False, verbose_name='Занято'),
        ),
        migrations.AddField(
            model_name='seat',
            name='not_book',
            field=models.BooleanField(default=False, verbose_name='Незанято'),
        ),
    ]
