# Generated by Django 2.2.28 on 2022-06-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performs', '0026_auto_20220604_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='title',
            field=models.CharField(default='sdsd', max_length=100, verbose_name='Название'),
        ),
    ]
