# Generated by Django 2.2.28 on 2022-06-04 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performs', '0027_seat_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perform',
            name='booked_seats',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
