# Generated by Django 2.2.28 on 2022-06-04 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performs', '0028_auto_20220604_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('seat_no', models.IntegerField(verbose_name='Номер сидения')),
                ('row_no', models.IntegerField(verbose_name='Номер ряда')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
        migrations.CreateModel(
            name='Seans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=30)),
                ('perform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performs.Perform')),
            ],
        ),
        migrations.CreateModel(
            name='Bron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forname', models.CharField(max_length=20)),
                ('row', models.IntegerField(default=0)),
                ('seat', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('seans_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performs.Seans')),
            ],
        ),
        migrations.AddField(
            model_name='perform',
            name='booked_seats',
            field=models.ManyToManyField(blank=True, to='performs.Seat', verbose_name='места'),
        ),
    ]
