# Generated by Django 2.2.28 on 2022-06-07 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performs', '0031_auto_20220607_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='title',
        ),
    ]
