# Generated by Django 2.2.28 on 2022-06-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performs', '0036_remove_perform_booked_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='session_seat',
        ),
        migrations.AddField(
            model_name='customuser',
            name='session_seat',
            field=models.ManyToManyField(related_name='session_seat', to='performs.SessionSeat', verbose_name='сеанс-место'),
        ),
    ]
