# Generated by Django 2.2.28 on 2022-06-07 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performs', '0037_auto_20220607_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionSeatStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус мест',
                'verbose_name_plural': 'Статусы мест',
            },
        ),
        migrations.RemoveField(
            model_name='sessionseat',
            name='booked',
        ),
        migrations.AddField(
            model_name='sessionseat',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='performs.SessionSeatStatus', verbose_name='Статус'),
        ),
    ]
