# Generated by Django 2.2.28 on 2022-06-07 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performs', '0038_auto_20220607_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionseat',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='performs.SessionSeatStatus', verbose_name='Статус'),
        ),
    ]
