# Generated by Django 2.2.28 on 2022-06-07 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performs', '0040_remove_sessionseat_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionSeatStatus',
        ),
    ]
