# Generated by Django 2.2.28 on 2022-06-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performs', '0041_delete_sessionseatstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionSeatStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус мест',
                'verbose_name_plural': 'Статусы мест',
            },
        ),
    ]
